M48
; DRILL file {KiCad 9.0.5} date 2025-11-21T21:05:52+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-21T21:05:52+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X55.0Y-55.0
X55.0Y-145.0
X145.0Y-55.0
X145.0Y-145.0
M30
